---
- hosts: all
  become: True
  gather_facts: false
  tasks:
    - name: Install prerequisites pt 1 run apt-get update and install python
      raw: "{{ item }}"
      loop:
        - sudo apt-get update
        - sudo apt-get -y install python
      become: true

